#! /bin/sh

#### AUTOSTART ####
sxhkd &
picom &
wal -i /usr/share/backgrounds/gnome/  &
/home/normie/.config/polybar/launch.sh &
synclient TapButton1=1 TapButton2=3 TapButton3=2 & #For laptop touchpad
# syndaemon -i 0.5 -t -K -R & #dissable touchpad while typing
xset -b & #For annoying beeping sounds
/usr/lib/polkit-gnome/polkit-gnome-authentication-agent-1 &
volumeicon &
nm-applet &
pulseaudio &
mopidy &
/home/normie/.local/bin/razer-cli -a &
xcompmgr &
devilspie -a &

#### WORKSPACES AND BORDERS #### 

# source the colors.
. "${HOME}/.cache/wal/colors.sh"

# Set the border colors.
bspc config normal_border_color "$color1"
bspc config active_border_color "$color2"
bspc config focused_border_color "$color15"
# Use the line below if you are on bspwm >= 0.9.4
bspc config presel_feedback_color "$color1"
# Use the line below if you are on bspwm < 0.9.4
#bspc config presel_border_color "$color1"

#Monitor allocation and their workspaces
bspc monitor -d a b c d e f g h

#Border gaps,width, and padding
bspc config border_width         3
bspc config window_gap          10
bspc config split_ratio          0.5
bspc config borderless_monocle   true
bspc config gapless_monocle      true
bspc config paddingless_monocle  true

bspc config top_padding          0
bspc config bottom_padding       0
bspc config left_padding         0
bspc config right_padding 	0

#bspc rule -a URxvt desktop='^1' follow=on
#bspc rule -a Subl3 desktop='^2' follow=on
#bspc rule -a Firefox desktop='^3' follow=on
#bspc rule -a Thunar desktop='^4' follow=on
#bspc rule -a Evince desktop='^5'follow=on

#Focus on pointer
bspc config focus_follows_pointer true
bspc config pointer_follows_focus false
