#!/bin/bash

## Created By Aditya Shakya

MENU="$(rofi -sep "|" -dmenu -i -p 'System' -location 3 -yoffset 32 -xoffset -10 -width 12 -hide-scrollbar -line-padding 4 -padding 20 -lines 4 -font "NotoSans Nerd Font Bold 12" <<< " Lock| Logout| Reboot| Shutdown")"
            case "$MENU" in
                *Lock) betterlockscreen -u /usr/share/backgrounds/gnome -l dimblur;;
                *Logout) bspc quit;;
                *Reboot)  reboot;;
                *Shutdown) shutdown -p now;;
            esac
